TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

PYTHON_SCRIPTS += scope.py

include $(TOP)/configure/RULES
include $(TOP)/configure/RULES_PY
